name: Build and Deploy to Cloud Run For Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/payment-ms-promptlabs:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/payment-ms-promptlabs:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy payment-ms-promptlabs \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/payment-ms-promptlabs:${{ github.sha }} \
        --region asia-southeast1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }},DEPLOY=PROD,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},STRIPE_KEY=${{ secrets.STRIPE_KEY }} \
        --max-instances=10 \
        --memory 1Gi 